### ISSUE TITLE
[Tracker] API Implementation

### ISSUE THREAD

**Issue by chrisvrose** [IEEE-RVCE/reforseti#27]
## API Implementation Progress
- [X] Home Route
- Auth
  - [x] Register - Now in POST `/api/auth/register`
  - [x] Login
  - [x] Logout
  - Logout all (Not used, not carrying over)
- Events
  - [x] Get all
  - [x] #45
  - [x] #45
  - [x] #45
  - [x] #45
  - [x] #45
- Society - #18 
  - [x] get all
  - [x] get one
  - [x] new
  - [x] delete
  - [x] edit
- affinities -> ~~Debating if its required. Please don't take subtasks under this.~~ Skipping
  - skip all
- Articles
  - [x] new
  - [x] get all
  - [x] get one
  - [x] delete
  - [x] #29
- Gallery
  - [x] get all
  - [x] get one
  - [x] #37
  - [x] #46
  - [x] #46
  - [x] #46
- Attendees
  - We **will** not carry it over.
- Execom
  - [x] Create one
  - [x] get all current for society
  - [x] get all past for society
  - [x] end tenure for society
  - [x] end for all
  - [x] get all current
  - [x] update 
  - [x] delete

**Comment by Prajwalprakash3722** [comment]
I can work on affinities, Society

**Comment by Prajwalprakash3722** [comment]
I might have missed mentioning this: if different societies collaborate for an event, it should be treated as a joint event, and the event should be associated with both societies.

**Comment by chrisvrose** [comment]
Good point. 

I think that support is not present in the database, we need to see if it can be added here separately or perform the change on both sides

**Comment by chrisvrose** [comment]
Not carrying over the logout all URL. It is useful but not used currently.

**Comment by chrisvrose** [comment]
We have coverage of all currently used APIs
